INSERT INTO public.users(username,password) VALUES 
('Maeve','123'),
('Luna','123'),
('Aurelia','123'),
('Eloise','123'),
('Isla','123'),
('Ophelia','123'),
('Aurora','123'),
('Eleanor','123'),
('Alice','123'),
('Ava','123'),
('Hazel','123'),
('Charlotte','123'),
('Elodie','123'),
('Iris','123'),
('Freya','123'),
('Amelia','123'),
('Clara','123'),
('Daphne','123'),
('Violet','123'),
('Bella', '123'),
('Thomas', '123'),
('Jared','123'),
('Octavio','123'),
('Leon','123'),
('Micah','123'),
('Josh','123'),
('Pete','123'),
('Casey','123'),
('Oliver','123'),
('Jackson','123'),
('Egor','123'),
('David','123'),
('Sadie','123');

INSERT INTO public.reviews(reviewcontents,user_id) VALUES
('This book was amazing!',1),
('This book was horrible!',2),
('This book was cool!',3),
('This book was bad!',4),
('This book was medium-ok!',5),
('This book was ok!',6),
('This book was iffy!',7),
('This book was terrible!',8),
('This book was the worst!',9),
('This book was the best!',10),
('This book was awesome!',11),
('This book was awe-some!',12),
('This book was my favorite!',13),
('This book was really cool!',14),
('This book was really bad!',15),
('This book was offending!',16),
('This book was bad !',17),
('This book was lorem!',18),
('This book was ipsum!',19),
('This book was dummy text!',20),
('This book was crazy!', 21),
('This book was gnarly!', 22),
('This book was gross!', 23),
('This book was insane!', 24),
('This book was off the chain bro!', 25),
('This book was bonkers!', 26),
('This book was knocking my socks off!', 27),
('This book was making me brain dead!', 28),
('This book was incredibly interesting!', 29),
('This book was eh.', 30),
('This book was tolerable.', 31),
('This book was decent.', 32),
('This book was fine and dandy', 33);

INSERT INTO public.books(isbn,name) VALUES
(1,'Acid for the Children'),
(2,'Once Upon a Time in Hollywood'),
(3,'The Storyteller'),
(4,'Watchmen'),
(5,'Harry Potter and the Sorcerers Stone'),
(6,'Braiding Sweetgrass'),
(7,'Blink'),
(8,'Truly Madly Guilty'),
(9,'1984'),
(10,'Fahrenheit 451'),
(11,'First'),
(12,'Lord of the Flies'),
(13,'Animal Farm'),
(14,'How to Win and Influence People'),
(15,'What the Dog Saw'),
(16,'Outliers'),
(17,'Heartbeat of Trees'),
(18,'The Prince'),
(19,'The Little Prince'),
(20,'War and Peace'),
(21,'Jane Eyre'),
(22,'Little Women'),
(23,'It Ends With Us'),
(24,'Becoming Me'),
(25,'Hunger Games'),
(26,'Mockingjay'),
(27,'Divergent'),
(28,'Allegiant'),
(29,'Insurgent'),
(30,'The Cat in the Hat');


INSERT INTO public.user_to_book(user_id, book_ISBN) VALUES
(1,3),
(1,6),
(1,8),
(1,2),
(1,25),
(1,28),
(2,12),
(2,14),
(2,6),
(2,2),
(2,1),
(2,10),
(2,4),
(3,5);
